version: '2'
services:
  main:
    build: ./main/
    command: bash -c "sleep 5; npm start" # wait rabbitmq start up
    links:
      - rabbitmq
    volumes:
      - ./main/:/app/
      - /app/node_modules
    env_file:
      - microservice.env

  worker:
    build: ./worker/
    command: bash -c "sleep 5; npm start" # wait rabbitmq start up
    links:
      - rabbitmq
    volumes:
      - ./worker/:/app/
      - /app/node_modules
    env_file:
      - microservice.env

  rabbitmq:
    image: rabbitmq
